### PR TITLE
i18n improvements and pt-BR translation

### PR DESCRIPTION
**Pull request by hvianna**
Changed the hook used to load the plugin's textdomain to
'plugins_loaded' so the title and description are properly translated on
the Appearance - Widgets screen ('admin_init' was too late);
Internationalized strings that were missing;
Created a .pot file for translators;
Added Portuguese (Brazil) translation files.

### CODE REVIEW

**Comment by hvianna** [comment]
Please note I have my text editor configured to automatically remove trailing spaces, so GIT generated a big diff for the **cat-posts.php** file. Actual changes on that file are only in lines 187, 1079, 1080 and 1183.

**Comment by markkap** [comment]
hi @hvianna tnx for submiting the PR . We used admin_init on purpose because we didn't want to load the text domain at the front end since we don't use any translatable strings there (not much of performance difference, just a principal of using things only when they are actually needed 😉 ) will look at it over the weekend maybe there is some more thing I need to learn about translations :)

**Comment by DanielFloeter** [comment]
Hello @hvianna, wordpress has a new online translation system at translate.wordpress.org. No more .pot and .mo files.

We would appreciate it, if you could create a Portuguese (Brazilian) translation.

For this I have to register your Wordpress-account (?) at Wordpress.org as a translator for Portuguese (Brazilian). And then you can confirm your translation. I am forbidden, for example, since I do not speak Brazilian.

**Comment by hvianna** [comment]
Hello, @DanielFloeter! Yes, you can add me as translation editor for pt-BR - I'll look into it during the week. My user on WordPress.org is [hvianna](https://profiles.wordpress.org/hvianna) as well.

**Comment by DanielFloeter** [comment]
Hi @hvianna, I have made a request for the permissions https://make.wordpress.org/polyglots/2016/11/27/hello-polyglots-im-the-author-2/
As soon as the authorizations are made I will write to you.

**Comment by DanielFloeter** [comment]
Helli @hvianna, can you try it here: https://translate.wordpress.org/locale/pt-br/default/wp-plugins/category-posts if you can approve translated strings. I see you here on the list as project translator: https://make.wordpress.org/polyglots/teams/?locale=pt_BR

Only the two stable versions.

**Comment by hvianna** [comment]
@DanielFloeter Nope, I don't see the option to approve strings. I'm translation editor to another project, but not a general editor, so I think I need to be assigned to this specific project.

**Comment by DanielFloeter** [comment]
Hello @hvianna,
now it should work: https://make.wordpress.org/polyglots/2016/11/27/hello-polyglots-im-the-author-2/

If you're interessted in you can write us a pm to http://tiptoppress.com/contact/ and we want to show you our appreciation.

**Comment by hvianna** [comment]
Hello, @DanielFloeter! The plugin strings are done, I'll keep working on the readme. I guess you can now close this PR.

P.S.: I replied to your previous contact via e-mail. Thanks again!

**Comment by DanielFloeter** [comment]
I hope so. (We received your e-mail.)

**Pull request closed without merging**
